name: Linting

on: pull_request

jobs:
  prettier:
    name: Prettier
    runs_on: ububtu-latest
    steps:
      - uses: actions/checkout@4

      - uses: actions/setup-node@4
        with:
          node_version: "lts/hydrogen"
      
      - run: npm ci

      - run: npm lint:prettier:check