name: Tests

on: pull_request

jobs:
  jest:
    name: Jest
    runs_on: ubuntu-latest
    steps:
      - uses: actions/checkout@4

      - uses: actions/setup-node@4

      - run: npm ci

      - run: npm test
